[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
crowdfunding = "Ept1VxEScf1bzfkwfEous1ZCDj16QCirBBq9kXzYAgwG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

# ADD THIS ðŸ‘‡ - Command to run test cases: solana-test-validator --rpc-port 9000 --faucet-port 9001 --reset
# [test.validator]
# url = "http://127.0.0.1:9000"
# faucet_url = "http://127.0.0.1:9001"
# ledger = ".anchor/test-ledger"
# bind_address = "0.0.0.0"
# reset = true

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
